### ISSUE TITLE
无法得到个性化的生成结果

### ISSUE THREAD

**Issue by JoshonSmith** [Rbrq03/ClassDiffusion#3]
根据开源的训练脚本和数据样例，无法得到个性化的生成结果

训练脚本：`scripts/train_single.sh`
训练数据：`data/dog`

训练完后，测试代码：

```
import torch
from diffusers import DiffusionPipeline

pipeline = DiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16,
).to("cuda")
pipeline.unet.load_attn_procs("ckpt路径", weight_name="pytorch_custom_diffusion_weights.bin")
pipeline.load_textual_inversion("ckpt路径", <new1>.bin")

image = pipeline(
    "<new1> dog swimming in the pool",
    num_inference_steps=100,
    guidance_scale=6.0,
    eta=1.0,
).images[0]
image.save("dog.png")
```

生成结果与训练集中的dog 完全不一致：
![dog1](https://github.com/Rbrq03/ClassDiffusion/assets/69639577/ca3e126e-9e08-4349-bfe3-8fc1df0116ca)
![dog](https://github.com/Rbrq03/ClassDiffusion/assets/69639577/3e2a5dcc-f3ab-44a8-9834-5678a62a648e)

**Comment by Rbrq03** [comment]
Hello @JoshonSmith, thanks for interest.
You should check whether PEFT is installed in your environment, as it results in a bug.
For more detailed, you can check [PR#7272](https://github.com/huggingface/diffusers/pull/7272), [Issue#7261](https://github.com/huggingface/diffusers/issues/7261). We are moving forward with this PR merge.
If you continue to experience issues, feel free to reach out.

**Comment by JoshonSmith** [comment]
> Hello @JoshonSmith, thanks for interest. You should check whether PEFT is installed in your environment, as it results in a bug. For more detailed, you can check [PR#7272](https://github.com/huggingface/diffusers/pull/7272), [Issue#7261](https://github.com/huggingface/diffusers/issues/7261). We are moving forward with this PR merge. If you continue to experience issues, feel free to reach out.

I install this diffusers:

`https://github.com/Rbrq03/diffusers/tree/custom_diffusion_peft_fix
`
this error is solved

**Comment by x2x5** [comment]
> > Hello [@JoshonSmith](https://github.com/JoshonSmith), thanks for interest. You should check whether PEFT is installed in your environment, as it results in a bug. For more detailed, you can check [PR#7272](https://github.com/huggingface/diffusers/pull/7272), [Issue#7261](https://github.com/huggingface/diffusers/issues/7261). We are moving forward with this PR merge. If you continue to experience issues, feel free to reach out.
> 
> I install this diffusers:
> 
> `https://github.com/Rbrq03/diffusers/tree/custom_diffusion_peft_fix ` this error is solved

Hi, I noticed in the readme that you mentioned if the environment contains PEFT, then it can't generate correct image. However, I create a new conda env, installing the official diffusers library, and didn't install peft, I'm still unable to generate the correct images.
So I don't know whether there are other modifications in your version of diffusers? 

<img width="512" height="512" alt="Image" src="https://github.com/user-attachments/assets/cdb14063-af40-4518-b839-0701bdd86a87" />

**Comment by Rbrq03** [comment]
We noticed this issue early this year. As we mentioned in #10, since diffusers change their code in this part a lot, we cannot identify the bug now. I recommend installing https://github.com/Rbrq03/diffusers for replacement.
